# Generated by Django 3.1.1 on 2020-10-20 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_auto_20200924_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('like', models.BooleanField(default=False, verbose_name='Лайк')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='blogApp.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Активность',
            },
        ),
    ]
