# Generated by Django 3.1.1 on 2020-10-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ip',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP'),
        ),
    ]
