# Generated by Django 3.1.1 on 2020-10-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_auto_20201020_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Активность', 'verbose_name_plural': 'Активность'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.AlterField(
            model_name='activity',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='IP'),
        ),
    ]
