# Generated by Django 3.1.1 on 2020-10-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_auto_20201020_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='like',
            field=models.BooleanField(default=False, null=True, verbose_name='Лайк'),
        ),
    ]
