# Generated by Django 3.1.1 on 2020-11-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_auto_20201105_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='like',
            field=models.BooleanField(default=True, verbose_name='Лайк'),
        ),
    ]
