# Generated by Django 3.1.1 on 2020-11-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0008_auto_20201107_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='like',
            field=models.BooleanField(default=False, verbose_name='Лайк'),
        ),
    ]
