# Generated by Django 3.1.1 on 2020-11-09 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0009_auto_20201107_2317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
